### ISSUE TITLE
Long Click-to-Tweets cannot be scrolled past on mobile. 

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#100]
From the user (iref.2610):

I am using your Click to Tweet widget and when I read an article on mobile and scroll down with my thumb, it won't let me go past a Click to Tweet quote. What's happening is that it is "clicking" on the quote rather than "scrolling" past it. 

[The click-to-tweet quote is large enough to cover the entire screen with no other room to touch outside the quote to scroll.]

**Comment by Nicholas-Cardot** [comment]
I have been unable to replicate this on multiple sites and on multiple different devices. This must be something being caused by the theme itself. Additionally, the updated version of event.preventDefault() function that I've built into the plugin may have already fixed this issue by stopping the default action.
