### ISSUE TITLE
Bitly shortening not working once activated

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#104]
A few users have reported that after entering their bitly credentials accurately, the link shortening doesn't work immediately.

**Comment by Nicholas-Cardot** [comment]
If the key here is "Immediately" then this is a null issue. The plugin only checks the Bitly settings and fetches the bitly links when the plugin data cache has expired. Meaning that if you activate bitly, the plugin will not make an attempt to update every link on every post across a website. Can you image how many API requests that would throw out all at the same exact time?

So instead, we only fetch those bitly links on the regular cache schedule that the rest of the plugin.

Since in 99% of cases, these credentials will be set up only once and then never looked at again, it means that the delayed population of the short links will only ever occur once at the very beginning and then never, ever again.

**Comment by DustinWStout** [comment]
I think we can call this "Sovled" then and create a Knowledgebase article with exactly that explanation. :dancer:
