### ISSUE TITLE
Images not aligning properly

### ISSUE THREAD

**Issue by kiffaniestahle** [warfare-plugins/social-warfare#156]
Since the last update, the images are not aligning properly. This makes it impossible to change them once they are uploaded. Here's a screenshot:

![screen shot 2016-05-04 at 11 07 31 am](https://cloud.githubusercontent.com/assets/15470387/15024191/c21ba374-11e8-11e6-9d0f-ef9d4ee4a60d.png)

**Comment by Nicholas-Cardot** [comment]
Have you cleared all your caches? It appears like it is using the our newest HTML structure, but still using the old CSS.

**Comment by kiffaniestahle** [comment]
Yes, both the WP and browser caches.

**Comment by Nicholas-Cardot** [comment]
This must be a unique conflict because I've got all the metabox CSS and Javascript very, very up-to-date and I've not heard about this from anyone else. I think this should be migrated to a support ticket so that we can track this as an individual issue rather than a plugin-wide systematic issue. We'll bring it back here if I need to after investigating it further.

Here's where you can drop a ticket if you haven't already done so: https://warfareplugins.com/contact-us/
