### ISSUE TITLE
Framebuster for Specific Pages

### ISSUE THREAD

**Issue by aaronbrosef** [warfare-plugins/social-warfare#208]
> Would it be possible to provide a setting to only use the framebuster on specific pages (or to provide exclusions)?
>
>The reason is that I want to iframe back to my own site from another site (to implement some tracking) but right now the framebuster obviously blows that up.
>
>Or if there's some sort of workaround I could use to block the framebuster on a specific page that would be great.

**Comment by Nicholas-Cardot** [comment]
There aren't enough use cases to implement this as an option in the plugin, however, the following line of code can be added to a functions.php file of your theme in order to make it do exactly what you want it to do.

$pages = array(1,2,3);
if( in_array( get_the_ID() , $pages ) ):
    remove_filter( 'swp_meta_tags' , 'swp_frame_buster' , 3 );
endif;

Of course, file the array with a comma separated list of IDs of the pages or posts that you want the frame buster removed from.
