### ISSUE TITLE
Wordfence Reporting Errors

### ISSUE THREAD

**Issue by terri2016** [warfare-plugins/social-warfare#221]
Wordfence is reporting about 20 errors, similar to these and I'm not sure if this is something I need to worry about or not. 

Modified plugin file: wp-content/plugins/social-warfare/social-warfare.php	
Modified plugin file: wp-content/plugins/social-warfare/script.js
Modified plugin file: wp-content/plugins/social-warfare/script.min.js
Modified plugin file: wp-content/plugins/social-warfare/functions/social-networks/whatsapp.php

**Comment by Nicholas-Cardot** [comment]
No. This is nothing to worry about. Those errors are because of how we push out "soft" updates. Basically, here's how it works:

Often we get a report of a bug that's only happening on one or two sites (or a small handful) so I push a bug fix to the repository but I don't change the version number on the plugin. This allows those users to get the update by deleting the plugin and immediately reinstalling it from the repository. But since I didn't change the version number, the other 4,000 users don't see the update. After I have a handful of changes to the plugin and those users have confirmed that the bugfixes have worked, then I change the version number which then pushes it out to everyone.

Your plugin is just checking your version's files against the files in the repository and finding that they don't match. If you want, you can delete the plugin and reinstall to get the latest version, but unless you're encountering one of the bugs that I've just fixed, this really isn't necessary. Instead, just wait for the regularly scheduled updates to come out and then update then.

Does this make sense?

**Comment by terri2016** [comment]
Thank you, that does make sense! I appreciate you letting me know.
