### ISSUE TITLE
Resizing the window breaks the sizes of the buttons when scales are in use.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#236]

**Comment by Nicholas-Cardot** [comment]
The scale adds a static width which is less than 100% (which is offset by the scale being larger than 100%). This static width needs to be removed before the resizing algorithm runs and then readded during the sizing.

**Comment by shadowlocked** [comment]
Agree this needs attention. Spoke with the developers, who contended that fixed device resolutions make this a non-issue. But I resize my browser a lot, and it's horrendous to see this break. Will wait for a fix before moving the latest version from staging to live.

**Comment by Nicholas-Cardot** [comment]
@shadowlocked Are you using one of the "Scale" options other than 100% as well? And every time you resize the buttons just get smaller and smaller?

**Comment by shadowlocked** [comment]
@Nicholas-Cardot No, every time I resize, the buttons get wider and wider, until the horizontal scroll width is absurd (3-4 times the natural width). 

The buttons were put into a custom position by our developers, and I haven't examined the code, except to note that prior to V2 this didn't occur. SW does have great commitment to custom placements, otherwise I guess this would be an unreasonable complaint.
