### ISSUE TITLE
Homepage display option

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#251]
We seem to have a lot of confusion regarding which option(s) control the display of buttons on the homepage. I think we could improve this by having a homepage-specific option under Position Share Buttons that does the following:

- Check the reading settings. If "latest posts" is chosen, display the buttons before/after each post in the loop depending on settings chosen (just like the archive/category settings)
- If a static page is selected, display the buttons as you would on any other page based on the settings chosen
- Disable the floating buttons completely unless the homepage is a static page - maybe change the floating dropdown to reflect either OFF or "ON and share the homepage URL". So basically if the homepage shows blog posts, there are no floating buttons, but if it's a page, there is an option to show floating buttons that share the homepage URL.

Just some thoughts. This part is very confusing for users and I think we would benefit from making it easier to know which setting affects the homepage versus other pages.

It may be worth it to do the same for a blog page if it's set in Settings > Reading. Just having the option to turn buttons on or off and choose different display options (maybe I want top and bottom on categories but only bottom on the blog archive) would go a long way.

**Comment by Nicholas-Cardot** [comment]
In an effort to clean up the workflow here on GitHub, we're moving all accepted Feature Requests (including this one) to our internal roadmap so that we can primarily use this space to track bugs, glitches, and plugin & theme conflicts that are occurring with existing features of the plugin. 

So although I'm closing this issue, I'm not dismissing it. I'm simply separating Bugs from Feature Requests by migrating feature requests over to where I'm tracking our roadmap. 

Sometime in the next week or so, we'll have a page up on our website where everyone will be able to publicly view the items (including this one) that we plan to either add to the core plugin or to build out as addons to the plugin. I'll make sure the link to that page is made available at that time.
