### ISSUE TITLE
Preview works on pages but not posts

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#252]
(iref 5814)

When previewing a **page**, the buttons display normally in the specified place when using the shortcode. Previewing a **post** does not display the buttons on preview, though they do appear as expected once the post has been published.

**Comment by Nicholas-Cardot** [comment]
This is not a bug. The plugin is designed to NOT display on a post until that post has been published. For the shortcodes to appear prior to publication, they need to be using the post_ID= parameter pointing to an already published post.

We do this because the networks will scrape the page and cache what they scraped. So if you click a share button on a non-published post, the network will attempt to scrape the page and then store 404 error data instead of being able to scrape your Open Graph tags and Twitter Cards and whatnot. This data will then be cached and when the post does become published, it will continue to contain the wrong information with the share until they get around to rescraping for fresh information.

To eliminate that from happening, we only display buttons for posts that are published.

Does that make sense?
