### ISSUE TITLE
Caching/transients for bit.ly link shortening

### ISSUE THREAD

**Issue by johnmontfx** [warfare-plugins/social-warfare#253]
I would love to use bit.ly shortening for both ease of use and click tracking, but we're rapidly running through our free requests per month in a manner of days. Based upon the traffic on the site, we can easily get over 4,000 bit.ly api requests in a day -- and we only have around 3,000 active articles on the site.

It appears as though new links are being generated on each display of the Tweet button (or at least very often). It would be great if the bit.ly request and result URL could be saved as a long term transient and flushed when when a post is updated with the save_post hook. This would save a tremendous number of requests (and API communication time).

**Comment by DustinWStout** [comment]
Hi John! I want to clarify exactly what happens when Social Warfare requests a Bitlink creation. 

First, it will check to see which social buttons you have on display. Then, for those that accept UTM parameters, it will add the UTM string appropriate to those buttons. Then if you have Bitly Shortening activated, for those networks that accept short URLs (I think Pinterest and Reddit are the only two that don't) the plugin requests a Bitlink to be created for each of those displayed buttons. It then stores that Bitlink in a custom field and serves it up every time. Unless the permalinks change or you make modifications to the UTM parameters (or change the activation status of them) there is no new Bitlink creation. Even if Social Warfare did (for some reason) request another Bitlink creation from Bitly, it would return the same short URL because Bitly knows when you're creating a Bitlink for a URL that you've already created one for. 

So let's say, for example, you have the Twitter, Facebook and Google+ buttons activated and you have UTM tracking on. Social Warfare would then request Bitly to create 3 Bitlinks per post. For 3,000 posts, that would be 9,000 Bitlinks created. But those links will never need to be created again unless you decide to either: 

1. Turn UTM tracking OFF
2. Change the UTM parameters

The other reason Bitly might be called again to create different links is if you have a custom URL set up through Bitly. If on the first attempt you've already exceeded your Custom URL limit for the month, Bitly would return with the standard bit.ly short URL. Then, next month when your custom URL quota is replenished, when the cache resets on Social Warfare, it would do a quick check to see if the Bitly link is using your custom domain, and if not it will have it created and store that version. At that point, no other Bitly link would ever be created for that post unless there is a permalink change or either of the two instances I noted above occurred. 

Hope that all makes sense.
