### ISSUE TITLE
Notice: Undefined index: reg_check in ... wp-content/plugins/social-warfare/functions/registration.php on line 54

### ISSUE THREAD

**Issue by sethbridges** [warfare-plugins/social-warfare#254]
I upgraded from a 1.x version to the latest (2.0.5) and now this error is printing to the top of the page body.

I see that there have been a number of other Undefined Index issues in the past, though none are open right now.

**Comment by sethbridges** [comment]
More details...I was just looking at the code that my server had after updating to 2.0.5.

There is what looks like debugging code in the file that doesn't match the .zip release from your github site.

Any ideas how this would happen?

@Nicholas-Cardot 

In registration.php:54
```
	if($_GET['reg_check'] == true):
		var_dump(swp_check_registration_status());
	endif;
```

**Comment by Nicholas-Cardot** [comment]
Yeah, I added that so that I could manually force the registration check to process. Once a month, the plugin pings our server back on our site to check if the user (you) still has a valid license that hasn't been canceled or expired. If I add ?reg_check=true to the end of a URL, it forces that check to run right there on the spot and then dumps the status to the screen so that I can view the response of that check. However, I should have checked to see if the variable exists first and then checked to see if it was set to true like such:

`   if(isset($_GET['reg_check']) && $_GET['reg_check'] == true):
        var_dump(swp_check_registration_status());
    endif;`

I'll make that change today.
