### ISSUE TITLE
Add ability to hook into swp_meta_tags filter before processing

### ISSUE THREAD

**Issue by johnmontfx** [warfare-plugins/social-warfare#258]
I'm trying to use Social Warfare on some custom pages of mine where I need to pass in some custom info for the URL and images. I've got everything working correctly, but I can't hook in before this in header-meta-tags.php:
`  add_filter( 'swp_meta_tags' , 'swp_open_graph_tags' , 1 );`

Would it be possible to increment the filter priorities by one on these so that users can adjust the info before the header generation is done? It doesn't seem like it would hurt other things.

Maybe even have each of the filter points an even number (2, 4, 6, 8, 10) so that we could insert inbetween? Though maybe that's over kill.

I'm just looking to adjust the info passed to the filter so it can be displayed correctly.

Thanks!

**Comment by Nicholas-Cardot** [comment]
@johnmontfx This is a great idea. Not only am I going to implement it, but I'm going to take it a step further.

First, I think I'm going to change them to multiples of 10. 10, 20, 30 will replace 1,2,3 and so on. This will allow people to hook in between any filter they want to.

Second, I'm going to break the Open Graph (and Twitter) generation hooks into two pieces each. The first hook will generate the values for each tag into an array. The second hook will take the values from the array and put them into the meta tag html tags necessary for output. This will allow people who want to do so to hook in between those two, set a value (for an image, for example) to something other than what the plugin generated. Then when it creates the HTML meta tag, it will use the value that you changed it to in between the the hooks.

Does that make sense and what feedback do you have about moving it in that type of a direction?

**Comment by johnmontfx** [comment]
That sounds absolutely fantastic...exactly what I needed (or need)! I ended up hooking into into the page_link filter (since get_the_permalink wouldn't include the query string) and having direct access to the URL would be great without having the need for an additional hook.

Now on to my next step, which is figuring out how to save and display the link share values for these URLs with query strings. :)

Thanks for listening.

**Comment by Nicholas-Cardot** [comment]
Can you elaborate on that last sentence a bit? Link share values? Because that might be in line with something I've already built but haven't released in the plugin yet. ;-)

**Comment by johnmontfx** [comment]
Well...since I've now got sharing of a WordPress page with a query string solved, I was hoping to display accurate share counts for that page. However, I see that you use the postid in the transient and that makes sense. 

There doesn't seem to be an easy way to get the "correct" share counts....and I understand this is really an edge use case :)

**Comment by Nicholas-Cardot** [comment]
What kind of query strings were you trying to add to it?

**Comment by johnmontfx** [comment]
The URLs are like this:
https://www.fxphd.com/details/?idCourse=217

I use a WordPress page called "details" but pass it the $idCourse variable to display information from a specific course....

**Comment by Nicholas-Cardot** [comment]
Ahhh. I see. Yeah, we won't be able to get the counts for those then. We store the counts in a custom field, but since it's only 1 page, every time you fetch the counts for a different variation, it would dump that new number right back into the same field that every other variation would be trying to use. Does that make sense?

**Comment by johnmontfx** [comment]
Totally -- I saw that in the code. Thanks for asking, but as I said I knew my use was very unusual.

I'm really happy about the new priorities for filters. I hate hacking original files...it's not the way to do things. :)

**Comment by Nicholas-Cardot** [comment]
In an effort to clean up the workflow here on GitHub, we're moving all accepted Feature Requests (including this one) to our internal roadmap so that we can primarily use this space to track bugs, glitches, and plugin & theme conflicts that are occurring with existing features of the plugin. 

So although I'm closing this issue, I'm not dismissing it. I'm simply separating Bugs from Feature Requests by migrating feature requests over to where I'm tracking our roadmap. 

Sometime in the next week or so, we'll have a page up on our website where everyone will be able to publicly view the items (including this one) that we plan to either add to the core plugin or to build out as addons to the plugin. I'll make sure the link to that page is made available at that time.
