### ISSUE TITLE
Pre-release bugs

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#273]
- [x] Pin button (static) on hover doesn't display "Pin"
- [x] Pin button (left-floating boxed style) Pin icon is off centered (to the left)
- [x] StumbleUpon button (left floating button style) doesn't show text on hover
- [x] Options page shows previous premium settings active when unregistered

**Comment by Nicholas-Cardot** [comment]
From Andrea:

 [ ] click to tweet still doesn’t work for me
 [ ] also i’m getting “success!” every time i go to the settings
 [ ] “sort dynamically by order of most shares” still not working 
 [ ] emphasize buttons not working
 [ ] weird jump is still there on the registration settings and the social identity settings when i scroll to the bottom  
 [ ] style settings still not working…. i’m wondering if i have the right version installed? because nothing is fixed  
 [ ] all the subsites on my multisite network unregistered themselves

**Comment by Nicholas-Cardot** [comment]
- [ ] The premium buttons that were set when registered do not go away when the plugin becomes unregistered

**Comment by Nicholas-Cardot** [comment]
For the premium options, I set the CSS to make the checkboxes appear in the "OFF" position when the plugin is not registered. The other text inputs, however, still display the content from when it was registered, but they are grayed out and not accessible. This should fix that confusion for the most part. 

And, of course, we'll revisit this as we rethink the display of all the premium options when the plugin is unregistered as per our conversation the other night.

**Comment by Nicholas-Cardot** [comment]
@nutsandbolts Can you give me a link to where you're testing this at so I can investigate those issues?

**Comment by robneu** [comment]
Found another one. It's a hold-over from the last version. You get undefined index warnings when the plugin is first installed.

**Comment by Nicholas-Cardot** [comment]
Are you fixing it or do you have some more information like the actual notices so that I can go ahead and fix it?

**Comment by Nicholas-Cardot** [comment]
Nevermind. Just saw your pull request. lol
