### ISSUE TITLE
Enable editing titles of sharing buttons

### ISSUE THREAD

**Issue by 88plug** [warfare-plugins/social-warfare#283]
Can you please enable editing the buttons text titles in the admin? For example we want to change "Email" to "Share a Hint". Thank you!

**Comment by Nicholas-Cardot** [comment]
Unfortunately this isn't practical because of the way that WordPress Core uses certain functions necessary for translations. So while you're only seeing Email, we also have a dozen or so translations for it. Making this feature would break the translations from how they work and from how they are supposed to work according to WordPress standards.
