### ISSUE TITLE
CTT Bitly character count is off by one

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#293]
From a customer (iref 6981):

> I was working with click-to-tweet last week, and looking to confirm the maximum character limit when using a standard bit.ly link so I could give my content team guidelines for tweet lengths. What I discovered was a 98 character limit (when you add the characters and spaces required by the bit.ly link).
> 
> When I pasted the a bit.ly URL into the click-to-tweet dropdown in the post editor, I was seeing a 99 remaining character limit displayed (when the true limit was 98). By all means, check my work on this - but I tested final tweet lengths on my Twitter homepage as well and confirmed the 98 character limit, so I’m pretty sure this is correct.

**Comment by mvasquez05** [comment]
Hi Nicholas i hope that you're very well, i want to report a bug with the whatsapp button in your social warfare plugin. Before i try to explain you the bug sorry for my english because i'm using google translator i hope you understand my words.
The problem is that after i make click over the Whatsapp button in my android smartphone this button disappear and also sometimes other social networks share windows are opened,  and the whatsapp application never opens, i want to show you this problem with a very short video with the hope you understand better in the following youtube link:

https://www.youtube.com/watch?v=kbDwFJgWH-A

Smartphone details:
Brand: LG, Model: LG Spirit, Android version 5.0.1, kernel version 3.10.54+, compilation number LRX21Y )

I have already tested the social warfare plugin with different wordpress themes and with everyone has the same problem so it is not caused by a specific theme.

Also i have already tested others plugins like "Easy social share buttons", "MashShare" and "Ultimate Social Deux", and in all these plugins the whatsapp button works perfectly in my LG Spirit smartphone.

Other big problem with the plugin is that if i add for example 10 ten social networks buttons, this buttons in mobile devices are shown in a very bad way ( too small ), this happen because there is not an option to show/hide the additional social networks, this can be easily solved with the inclusion of an option to show the '+' PLUS button at the end of the share bar to show/hide the secondary/other social networks. You can check how the MashShare plugin implement this feature. This is a essencial feature because there are many users who want to display more than 5 social networks and in mobile devices the horizontal space is very limited.

One suggestions to improve your great plugin:
1. Please implement the LikeAfterShare functionality like the plugin Mashshare already do.

Thanks in advance, and i hope you can fix this whatsapp bug and add the '+' PLUS button option to show/hide the secondary social networks at the end of the share bar as fast as possible,

Best Regards,
Miguel

**Comment by Nicholas-Cardot** [comment]
Twitter doesn't use Bitly links. They wrap them all in there own links. So we take the length of the twitter shortlinks, plus 1 (for a space before or after) and that's how we calculate the available characters.

**Comment by Nicholas-Cardot** [comment]
But I'll double check this on our beta site and see if I can replicate the same results. If so, I'll adjust the counter accordingly.

**Comment by Nicholas-Cardot** [comment]
So it seems that this is because of the via @username being added. But ours is most likely accounting for one extra space than they are which we do because there needs to be a space prior to the word "via"

**Comment by Nicholas-Cardot** [comment]
Yup. I just confirmed. The output from the CTT when copied directly into Twitter's share box has the exact same characters remaining as the CTT generator in SW.

**Comment by Nicholas-Cardot** [comment]
Here's how you can test this:

1. Create a click to tweet.
2. Remember the number of characters SW says is remaining.
3. Go to the post.
4. Click on the Click to Tweet.
5. Check if the Twitter share dialogue right there has the same number as SW's number.

If not, then we can continue troubleshooting. Creating your own share on Twitter.com may not accurately reflect the exact message that SW is creating on the Click to Tweet. So be sure to test the message that is actually being output by SW's CTT.
