### ISSUE TITLE
Pin It hover description can't handle special characters

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#324]
(iref 8168)

If an image alt tag contains a special character such as an ampersand, the Pinterest description will be cut off when using the Pin It hover button.

**Comment by Nicholas-Cardot** [comment]
1. The function that controls this is located in js/script.js. However, the version that goes out to the public and is loaded by the plugin is /js/script.min.js. However, we have a URL parameter that allows you to load the unminified version for testing and development. The URL parameter works like this: mysite.com/my-blog-post/?swp_debug=script

2. Don't worry about minifying the file after you update the function. Just make sure it's working in the unminified version and I have a tool that I'll use after I merge it back in that will port all of your changes over to the minified version after I review it.

3. The special characters most likely just need some type of URL encoding applied to the string in order for them not to break.

4. Submit a pull request once you're finished so that I can review and pull it back in.

**Comment by scott-wiser** [comment]
Your right, the solution is likely going to be encoding the ampersand as %26.

I wonder if there is anything else that makes it's way into the descriptions or url that might need to be encoded.

I'll test this tomorrow (or today) and have a commit uploaded for the ampersand, and see if I can identify any other use cases where encoding is needed.

**Comment by Nicholas-Cardot** [comment]
Is there a function that can be used to catch all special characters and make them friendly to the URL link that they are in? Some sort of a url_encode or something?

**Comment by scott-wiser** [comment]
Yeah, we have some builtin options:

This thread explains it nicely:
http://stackoverflow.com/questions/332872/encode-url-in-javascript

I'm looking at the code now and setting up a test.  Apparently encodeURIComponent() is the best bet except for a few characters

**Comment by scott-wiser** [comment]
I've confirmed the problem in my local test system.  Here is a screenshot with it on the Pro version using the Pin
![propinitampersand](https://cloud.githubusercontent.com/assets/26015152/23977088/31062fbc-09a9-11e7-8c30-79220cc872d8.JPG)

If you can see that screenshot, the actual ampersand has a "amp;" after it.  Likely from Wordpress, this leaves the ampersand in tact.

The Pinterest system receives the ampersand and confuses with the marking of a new parameter, cutting off the description.

I'll have an update on an attempt to solve the problem in the relevant Javascript function.

**Comment by scott-wiser** [comment]
I'm making a commit which fixes the ampersand issue for both the image alt and the image title attributes.

**Comment by scott-wiser** [comment]
This screenshot shows how a image title and alt attribute show visible ampersands now in the Pinterest saver, whereas before they didn't.

The description just needed to be encoded.
![pinitfixedampersand](https://cloud.githubusercontent.com/assets/26015152/23977868/05e92e2e-09ae-11e7-9904-17180a878e52.JPG)

**Comment by scott-wiser** [comment]
This commit has the change:
https://github.com/scott-wiser/social-warfare/commit/f0ec6c9f7d9f301d2f846e3afef174a1b59e7eb1

**Comment by Nicholas-Cardot** [comment]
This is now fixed.
