### ISSUE TITLE
og:image - blank images ing Linked In shares when the filesize of original image exceed 1MB

### ISSUE THREAD

**Issue by fvrichard** [warfare-plugins/social-warfare#334]
Hi,

we noticed issue when we want to share post to Linked In network. The **og:image** tag is using original image size. If the original image size exceed size 1MB, the Linked In displays blank image because of restrictions:
https://www.linkedin.com/help/linkedin/answer/46687/making-your-website-shareable-on-linkedin

We are suggesting fixing this with using "large" image size instead.
Also, add the og:width and og:height tags which are currently empty.

_social-warfare-pro/functions/header-meta-tags.php_ - changes have been done on lines 184-187

I'm pasting here whole block of code with fix:

ORIGINAL CODE:
```
	/**
	 * Open Graph image
	 *
	 */
	if ( !empty( $custom_og_image_url ) ) :
		$info['meta_tag_values']['og_image'] = $custom_og_image_url;
	elseif ( !empty( $yoast_og_image ) ) :
		$info['meta_tag_values']['og_image'] = $yoast_og_image;
	else :
		$thumbnail_url = wp_get_attachment_url( get_post_thumbnail_id( $info['postID'] ) );
		if ( $thumbnail_url ) :
			$info['meta_tag_values']['og_image'] = $thumbnail_url;
		endif;
	endif;
```

FIXED CODE:
```
	/**
	 * Open Graph image
	 *
	 */
	if ( !empty( $custom_og_image_url ) ) :
		$info['meta_tag_values']['og_image'] = $custom_og_image_url;
	elseif ( !empty( $yoast_og_image ) ) :
		$info['meta_tag_values']['og_image'] = $yoast_og_image;
	else :
		$thumbnail_data = wp_get_attachment_image_src( get_post_thumbnail_id( $info['postID'] ), 'large' );
		if ( $thumbnail_data ) :
			$info['meta_tag_values']['og_image']         = $thumbnail_data[0];
			$info['meta_tag_values']['og_image_width']   = $thumbnail_data[1];
			$info['meta_tag_values']['og_image_height']  = $thumbnail_data[2];
		endif;
	endif;
```

Thanks,
Richard
Foliovision

**Comment by DustinWStout** [comment]
Hi @fvrichard! Thanks for putting this solution together and suggesting it. The reason we can't force the use of WordPress' Large Image size is because that would mean that it requires a user to ensure that the Large image inside their WordPress media settings is to the optimal size of their most important social network. For example, an optimal Facebook image (to properly show the big landscape image) needs to be 1200x628 (or similar ratio). 

Most users will have not modified their Media settings meaning that the Large Image size is 1024x1024 and definitely NOT the ideal size for social media Open Graph output. 

Additionally, in the plugin upload box we recommend the 1200x628 size for Social Media images. I can't imagine that images that are within these dimensions should exceed 1MB in size. If they are, I highly recommend putting them through image optimization-- Imagify.io is a free and highly effective solution which also has WordPress integration.
