### ISSUE TITLE
Removed url parameters when sharing

### ISSUE THREAD

**Issue by Ciao121** [warfare-plugins/social-warfare#335]
If I try to share an url like:
`http://www.example.com/post/?video=1
`the opened popups try to share (facebook example)
`https://www.facebook.com/share.php?u=http%3A%2F%2Fwww.example.comt%2Fpost%2F`
removing ?video=1

Is there any way to have it sharing the full url?
Thank you!

Add... If I manually share the url on facebook parameters are correctly evaluated

**Comment by Ciao121** [comment]
For fb I solved replacing
```
$array['resource']['facebook'] .= '<a rel="nofollow" target="_blank" href="http://www.facebook.com/share.php?u=' . $link . ' data-link="http://www.facebook.com/share.php?u=' . $link . ' class="nc_tweet">';
with
`$array['resource']['facebook'] .= '<a rel="nofollow" target="_blank" href="http://www.facebook.com/share.php?u=' . $link . '?my_parametername='.$_GET['my_parametername'].'" data-link="http://www.facebook.com/share.php?u=' . $link . '?my_parametername='.$_GET['my_parametername'].'" class="nc_tweet">';`
```

Probably the same for others socials buttons.

**Comment by Nicholas-Cardot** [comment]
This seems to be a fringe use case and it appears that whatever plugin or theme that you are using is not properly adding those url parameters to the proper WordPress URL hooks. We use the get_permalink( $postID ); which is a native WordPress function for fetching the URL of a page. If the URL parameters are not added to the correct filter, then that function will not return the URL with the parameters and there's nothing that we can do about that at our end.

Additionally, the fix for that would break nearly every other configuration out there because it specifically targets this fringe use case and will not suffice as a universal fix. I would recommend that you use this fix for you site, but it's simply not feasible to add this to the core of the plugin.
