### ISSUE TITLE
Option to Add Custom Pinterest Image/Description on the page

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#344]
There's a great tutorial from Kristie Hill about adding a Pinterest image to the page that will be picked up by the Pinterest Browser Extension as well as other Pinterest-oriented Browser Extensions (such as Tailwind). Her post can be found [here](http://blogambitions.com/how-to-hide-pins/).

In it she shows that you can add the following parameters to an image: 

data-pin-url=" "
data-pin-media=" "
data-pin-description=" "

So for example, an image might look like this: 

`<img src="http://blogambitions.com/wp-content/uploads/2017/02/hide-a-pin.png" alt="Computer with pinterest feed." data-pin-url="http://blogambitions.com/hide-pins" data-pin-media="http://blogambitions.com/wp-content/uploads/2017/02/how-to-hide-a-pin.png"
data-pin-description="Hide pinnable images in your blog posts without ruining the flow and branding of your posts" />`

It seems like this would be relatively easy to add as an option to Social Warfare - Pro.

Further reading from the [Official Pinterest Blog](https://business.pinterest.com/en/blog/pin-it-button-technical-tune-5-tips-make-sharing-your-site-better).

**Comment by Nicholas-Cardot** [comment]
The only problem with this is that this adds an <img> tag to the page. So even though the image is invisible, it still adds an additional http request to the page along with the extra KB necessary to load that page for each page load. Perhaps this should be an option in the settings that people can toggle on and off with a brief explanation of what it does?

**Comment by DustinWStout** [comment]
@Nicholas-Cardot I think that would be a good idea. Maybe just a checkbox on the metabox even? Something like:

> Also insert Pinterest image into the page for 3rd party sharers? 

The idea behind this isn't that it needs to be hidden from the page. Bloggers like Kristie actually prefer having it somewhere on the page so that those using the Pinterest Browser Extension (and other 3rd party sharing tools) will see the image and be able to pick up on it.

So I guess the *best case* would even be to have this option in the WordPress media uploader interface? But I think a checkbox in the SW metabox would do as well. Then maybe it can insert the image at the bottom of the post in a discreet way? We should definitely talk about this at our next staff meeting.

**Comment by Nicholas-Cardot** [comment]
I've spent a lot of time trying to figure out how to add meta fields to the image upload area, and I keep coming up short. I think the easiest way for this would be one of the following two options:

1. We add a toggle in the Social Warfare Custom Options at the bottom of each post.
2. We simply add a toggle on the Admin Options page and then, if activated, do this site wide on any posts that the customer has added a custom Pinterest image.

I think the second option is probably the best solution. I imagine that people will most likely want this feature on site wide or not at all. I can't imagine that they would want to have to go back and add it individually for every single post. Using that option would automate it across their entire site with one single click. Thoughts?

**Comment by nutsandbolts** [comment]
People ask about this ALL the time. Usually they already have a hidden image in every single post EVER and they get upset because SW can't pick it up. We should (ideally) be doing a check to see if there is already a hidden image before looking to the custom options for the Pinterest image.

**Comment by Nicholas-Cardot** [comment]
I'm not sure how to detect if they already have a manually placed hidden image. I think the following workflow should fix this issue though:

Admin Options Page:
Option 1: Do you want your Pinterest image added to each post so that third-party browser extensions will use your optimized Pinterest image when user's share your post? On/Off
Option 2: Where do you want the Pinterest image to appear on the page? Hidden/At the Top of the Post/At the Bottom of the Post

Post Options:
Option 1: Do you want your Pinterest image added to the post so that browser exensions will use it for Pinterest shares? Default / On / Off
Option 2: Where do you want the Pinterest image to appear on this post? Default / Hidden / Top / Bottom

This is what Dustin and I just discussed on the phone. I think that with this set of options it should satisfy every possible use case that people may want. 

1. This allows for the simplest possible implementation site wide. Simply set it in the admin options and leave all post options to default (default meaning that it pulls the settings from the admin option page).
2. This allows for people who want per-post control to have that control.

Hence, both camps can be fully satisfied.

@nutsandbolts Thoughts?

**Comment by Nicholas-Cardot** [comment]
@dustin and @andrea  When you get a minute, can you look at the new Social Warfare Custom Options on the post editor on the beta site. I added the two fields for the new Pinterest options. Also, @andrea you haven't seen the new options on the Advanced tab of the Admin Options Page so please have a look at your convenience. We'll be adding a link to a knowledge base article prior to release.

Bear in mind 2 things on the post options settings. 1. I wanted all the Pinterest options to be together and 2. I wanted all 4 of the dropdown select options to be grouped together. With that in mind, I moved the Custom Tweet up one spot, brought the Pinterest descriptions down one spot, and put the two new options right under the Pinterest description.

I also changed the size of the select boxes so that they are the exact same size now. They don't quite line up perfectly on the right hand side, but at least they're all consistent so I think that's the best we can do unless one of you wants to toy with the css size just a bit if you think you can make it line up better on the right for those boxes.

The last and final step that I'll do tomorrow morning is to actually output the image to the page. That shouldn't take too long though.

**Comment by DustinWStout** [comment]
We should play with Flexbox to help better align these new options.

**Comment by Nicholas-Cardot** [comment]
This is now committed and ready for testing.

**Comment by Nicholas-Cardot** [comment]
1. Make the post specific options work.
2. Make the hidden image stay hidden. Currently the pin wrapper is being overridden with CSS set to display:table!important. If I add no_pin to the hidden one, that should go away immediately.

**Comment by Nicholas-Cardot** [comment]
This should now be fully completed and should be safe to release as a beta feature.

**Comment by Nicholas-Cardot** [comment]
Tested and working. Closing issue.
