### ISSUE TITLE
Pinterest Hover Save Button Description

### ISSUE THREAD

**Issue by lvvvvvl** [warfare-plugins/social-warfare#349]
Hey,

I've updated the new version and now the Save hovering button works well with WP-Rockets image lazy load.

One of the bugs I've noticed now is that the description used to share the image when someone clicks "Save" is actually the ALT text instead of the description I've written in the Social Warfare posts settings. 

When someone uses the share on pinterest button, it does use the description. But when someone tries to use the Save image hover button, it uses the ALT text as description.

Is this a known bug?

Thank you.

**Comment by Nicholas-Cardot** [comment]
This isn't a bug. This is literally how every other Pinterest plugin and browser extension that adds pin buttons to images works so we made ours use the alt tag as well so that any users switching from another Pinterest plugin to ours would not have to make any changes and would be able to transition seamlessly to ours and be able to continue with the same methodology that they used prior to using ours.
