### ISSUE TITLE
 Can't find variable: socialWarfarePlugin

### ISSUE THREAD

**Issue by phpbits** [warfare-plugins/social-warfare#356]
JS error on line 551 : socialWarfarePlugin.fetchShares();
<img width="976" alt="screen shot 2017-04-04 at 11 30 05 pm" src="https://cloud.githubusercontent.com/assets/3365507/24664605/b3c0dc10-198d-11e7-8665-3c5093d7a21b.png">

**Comment by Nicholas-Cardot** [comment]
I don't think this is a bug; it needs to be submitted to support before being brought here to GitHub. Most of the time this error creeps up, it's because another plugin is loading a second and separate version of jQuery and not using WordPress's enqueue process to do it.

This leads to the following process:
1. jQuery and all of it's functions are loaded.
2. Our plugin adds a function on top of the jQuery library.
3. The second jQuery gets loaded overriding the first (including our function) and then loads its own version.
4. We try to call the function but it now no longer exists.

Check the source code to see if two versions of jQuery are being loaded. If so, immediately get rid of the plugin or theme that is causing that second one to load. It's a horrible practice to load jQuery that way and it will almost always break something.
