### ISSUE TITLE
OG type tag

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#357]
A customer pointed out today that all SW OG tags assign a type of "article" - this is fine for blog posts or pages but can be a problem for things like products. I'm wondering if we should consider allowing the type tag to be set on a per-post-type basis but open to other suggestions to manage this.

**Comment by Nicholas-Cardot** [comment]
Oh, that would actually work, I suppose. I never wanted to add that feature because the only solution we were going to go with before was adding it to the post editor options, but since 90% of posts are "articles" it seemed too much hassle. But if we just make it on the admin options page as a one off setting for each post type, that would be much, much better. However, even if I do add this, I DO NOT want to add it to the post editor also because those options I want to keep as simple as possible.

Also, they can also use a filter to change the value of it as well.

**Comment by nutsandbolts** [comment]
Agreed - per-post is a little much I think, but being able to call ALL recipes "recipes" or whatever makes good semantic sense.

**Comment by nutsandbolts** [comment]
Also if there is a filter, do we have a doc for it? I didn't know about that one.

**Comment by Nicholas-Cardot** [comment]
add_filter( 'swp_header_values' , 'my_custom_post_type_og_tag'    , 15 );
function my_custom_post_type_og_tag($info) {
    // Add a condition here that checks the post type and makes a value in $og_type
    $info['meta_tag_values']['og_type'] = $og_type;
    return $info;
}

**Comment by Nicholas-Cardot** [comment]
This is now complete. The user can now select a different default tag for each post type. Additionally, these values can always be overridden by creating a custom field called "swp_og_type" and populating it with a value consistent with the recegnized og:type values listed in Facebook's Open Graph documentation.
