### ISSUE TITLE
Sharing Category Pages Might Only Share First Post

### ISSUE THREAD

**Issue by scott-t-11** [warfare-plugins/social-warfare#366]
REPORTED TICKET #8218
Issue: When trying to share the category page itself, it actually shares the latest blog post in the category instead of the page itself. Is it possible to share the pages as a whole instead of the latest blog? We like people to be able to share the pages as well.

**Comment by nutsandbolts** [comment]
We've had this discussion a couple of times (before you came on board)... Basically right now any archive page is set up so that, if the buttons are enabled for categories/archives, each post on the archive will have its own set of sharing buttons. It's far more common for someone to share an individual blog post instead of "Hey, check out this category of articles." 

Since archives aren't an actual page with an ID, the plugin (as it is currently) doesn't know what to share, so the shortcode will grab the first available Open Graph tags on the page. The debate we've had in the past is whether it makes sense to restructure the whole plugin to share archive pages (instead of individual posts from the archive) when only 5% of users want this functionality.

**Comment by Nicholas-Cardot** [comment]
Yeah, I doubt that it is even 5%. Maybe we will revisit this at a later time, but for now, just tell customers that the plugin is designed to share posts and pages, and not archive pages.
