### ISSUE TITLE
Left side total has display issues

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#384]
(iref 10149)

The 2.2.5 update has resulted in some odd behaviors when the total is on the left. The word "shares" is cut off and the total has a border on hover. Customer submitted some screenshots and you can see the border on hover here: https://beta.warfareplugins.com/sample-page/

I couldn't replicate the cut off "shares" but this could be a letter-spacing issue or a situation where the theme font is taking over. We need to make sure our CSS for the text is specific enough not to be overridden.

**Comment by nwilson99** [comment]
Since the latest update the shares are not being displayed at all for me. Old posts show their share numbers (certainly at least as they were before the update anyway) but new posts have no share count at all even though I know they have shares that should be showing. It is possible with me that if twitter counts were not being recorded then no shares would show, so I don't know if it is a count issue with twitter only and / or all other social media outlets.
