### ISSUE TITLE
Use font-awesome

### ISSUE THREAD

**Issue by Mte90** [warfare-plugins/social-warfare#430]
Today Font-awesome is used in a lot fof theme and plugins, this plugin load a specific font only with social logos and in my site I have font-awesome complete with everything.
It will be useful for performance not load again another font and support font-awesome.

**Comment by DustinWStout** [comment]
Hi @Mte90! We've gotten this request quite a bit, and here's why we continually choose not to utilize Font Awesome (or any other popular icon font):

1. We do not control it, therefore we cannot guarantee its quality. When a social network changes its logo, we want to update it immediately to guarantee our users always stay current in their look. Font Awesome has been known to keep outdated brand icons for far longer than I'd be comfortable with on my own properties, let alone that of our users. 

2. We would still need to load additional icons. Because we cannot tell Font Awesome (or other icon sets) what icons to include, specifically our own branded icons, we would still need to load a separate icon font, thereby creating more loaded resources.

3. Potential for conflict with different versions. When we own the icon font, we control the version compatibility. As you said, **many** themes and plugins utilize Font Awesome, and with so many implementations, version conflicts are more and more probable. We're eliminating that potential. 

4. Our icon font is tiny... like SUPER tiny. And therefore, shouldn't even be a factor if you're worried about load time/resources. 

Hopefully, that helps explain our rational and give you a better idea of how we're looking out for the best interests of all users from every angle.
