### ISSUE TITLE
Optimize the caching mechanisms to reduce server load

### ISSUE THREAD

**Issue by Mte90** [warfare-plugins/social-warfare#433]
I am trying to understand on my server why we have a lot of access to admin-ajax.
I saw that during the day there are a lot of requests to:

- swp_facebook_shares_update
- swp_cache_trigger

I am wondering if we can switch this kind of requests as a nightly cron to run every day (we have also the pro version of the plugin).

**Comment by DustinWStout** [comment]
Hi @Mte90! So, what you're seeing there is the share counts cache updating. These share count caches are updated according to a [predefined schedule](https://warfareplugins.com/support/i-just-shared-the-post-but-the-numbers-didnt-update-why-not/) and only triggered by a page load. Since most people want their share counts to be as accurate as possible, and as close to "real time" as possible" we don't currently have a way to just have them update once per night. 

@Nicholas-Cardot may be able to shed more light on this, but perhaps this could be handled with a hook/filter?

**Comment by Mte90** [comment]
Yes I understand the real time issue but for our needs, on cron (for everything) will be enough and we will avoid all the `admin-ajax.php` calls.
Also as wp-cli will be nough :-)

**Comment by DustinWStout** [comment]
@Mte90 again, @Nicholas-Cardot will have a better technical grasp on the practicality of this. However, it's important to understand that you should ONLY fetch new counts for pages that have actually been visited. You don't want every page on your site pinging the social network apis at the same time... you could get banned/blacklisted for too many api calls. Not to mention that running them all at once might be a heavy load on your server (depending on how many pages need cache updates). This is why we built the "on page load" trigger in the first place--to use the minimal amount of server resources and only when needed.

**Comment by Mte90** [comment]
I will wait for more technical info.
Now we disabled the advanced cache and we will see if there are less calls.

**Comment by mkrampf** [comment]
Are there any updates on this? I have the paid plugin that I turned on a few days ago. It floods my server with requests to admin-ajax.php, with a post to action=swp_facebook_shares_update&post_id=777&activity=13892, and literally brings down my site due to so many requests. I have hundreds of users on my site at any one time until the site goes down. Disabling advanced cache does not seem to help. I emailed support and have not received a response.

**Comment by mkrampf** [comment]
@nutsandbolts I sent it as a reply to an existing request this morning at 10:45 CST. I know it was the right email because we already went back and forth a few times. It was a response to an existing ticket. The ticket # is 16730. Please advise?

**Comment by nutsandbolts** [comment]
@mkrampf Our developers have the ticket in their box and will respond as soon as possible. It’s likely they didn’t see your response before leaving for the day, as only part of their time is spent in support. We commit to a response within 24 hours in most situations.

**Comment by Nicholas-Cardot** [comment]
This should now be fully resolved.
