### ISSUE TITLE
Add CSS to Pinterest image when displayed at top or bottom of post

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#458]
# **Notes for Testers** 
***Updated on 20 AUG 2018***

### What we want to happen: 
When inserting a Pinterest image to the post, there should be space above or below so it isn't up against the content. 

#### Bonus
We now have a CSS class to target the Pinterst Image for custom CSS: `.swp-pinterest-image`. 

### Step 1: Add a Pinterest image to the post using the Social Warfare metabox. 
1. In the post editor, insert an image for the Pinterest image section. 
2. Set the location to "top". 
3. Press save the changes by pressing "Update."

### Step 2: View the post. 

If the content is almost touching the image, let us know. 

### Step 3: Change the location to "bottom". 

If the content is almost touching the image, let us know. 

### Step 4: Give it custom CSS.

In Appearance -> Customize -> Additional CSS, use the `.swp-pinterest-image` CSS class to style the image. Do whatever you want to it, we just need to make sure that you are able to edit the image's style with this class. 

#
If all of the above checks out, hooray! Give this a thumbs up. 
If something goes awry, please let us know as a comment to this issue. 

# **Original Issue**

When the Pinterest images aren't hidden, we really need to add some margin so they aren't right on top of the content (this is super noticeable when the image is at the bottom of the post). 

We should also consider a way to let people set the size and alignment for the images - they're enormous and I have to provide CSS to resize them constantly.

**Comment by Nicholas-Cardot** [comment]
@nutsandbolts I understand the spacing issue, we can solve that with some margin or padding pretty easily. However, can you be more specific regarding what kind of sizing and alignment options that customers are asking for? Some more specific input would make this much easier to get implemented. Thanks!

**Comment by nutsandbolts** [comment]
Sorry, I thought that was pretty specific - alignment (left, center, right) is a WP core functionality that all themes have CSS for already. Width and height are also common attributes.

**Comment by ckmahoney** [comment]
Here is a screenshot of the Pin image at the top of a post: 

<img width="1920" alt="screen shot 2018-08-06 at 1 01 14 pm" src="https://user-images.githubusercontent.com/26120849/43730282-e2f058fa-9978-11e8-9219-c4ed1cf49810.png">

And at the bottom of a post:


<img width="1920" alt="screen shot 2018-08-06 at 1 00 09 pm" src="https://user-images.githubusercontent.com/26120849/43730295-e7dc3d0c-9978-11e8-84c2-3e04241f23ed.png">

#

Yes, the top is a bit close to the content. The bottom seems reasonable to me. @DustinWStout, this is ultimately your call. What say you? 

And yes, the image is pretty large. Should we offer the WP image sizes as options? Thumbnail, medium, medium_large, large, full. 
If medium_larger or smaller, offer positioning options (left, center, right)

cc @nutsandbolts

**Comment by DustinWStout** [comment]
@ckmahoney hmm... that's a hard call to make because I assume (maybe wrongly) that people's themes should have image/paragraph padding/margin built-in and wouldn't want to mess with that. however, I think the minimum space between top/bottom of an image should be 20px. 

And **no** on the WP image sizes. The people using this _should_ know that the image needs to be ideally 600x900 (or 735x1102) or a similar landscape orientation in order for the image to perform well on Pinterest. I expect none of the WP image sizes are built to optimize that.

**Comment by nutsandbolts** [comment]
People don't want to resize the custom image - they want to resize it in their posts so there isn't this MASSIVE image at the top or bottom. They want to display it at one size and pin at full size.

**Comment by nutsandbolts** [comment]
We'd be better off offering percentages like we do for the buttons. Just let them shrink it down so it doesn't take over the entire post.

**Comment by DustinWStout** [comment]
@ckmahoney We really don't want to pull from the WP image sizes because we have no idea what each install's media settings will be. It's a crap shoot. 

I still don't want to mess too much with CSS or have any sort of extra JavaScript in there sizing things, adding more potential for bugginess or conflicts. 

Best option is to simply make sure the pinterest image is fitting within its given container (the content area) and make sure there's ample space (margin) above and below the image as it will be inserted before/after paragraphs.

**Comment by nutsandbolts** [comment]
I still like the idea of percentages because that starts with the original Pinterest image size as a base and just shrinks or stretches proportionally.

**Comment by ckmahoney** [comment]
Annotated with notes, this is ready for testing.
