### ISSUE TITLE
Add an alternate on-page-load cache trigger option

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#46]
Some folks who don't get a lot of traffic aren't getting their cached counts reset very often. In some of these cases, they prefer to have the numbers regenerate and show the updates on the page load rather than being triggered after the page load.

**Comment by John-Dietrich** [comment]
Yes, this would be very helpful since it would be a way for companies with many blog posts to display share counts on the blog posts pages. Currently, someone has to actually load each individual blog post for the API call to be made and the share counts to display. An option in the Social Warfare plugin to enable this functionality would be greatly appreciated!
