### ISSUE TITLE
Add manual recovery URL field to the per-post custom options

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#513]
I hand out a LOT of instructions for manually defining a recovery URL, which involves multiple steps including manually installing a repo plugin that is so old it can't be searched out in the Add New plugins screen. It's very frustrating for customers because they aren't familiar with custom fields or how to add a new one.

I think it would make a lot of sense to have a field in the custom options where someone can enter a manual recovery URL if needed. Maybe this can be toggled on/off via the main recovery settings, and it only shows in the editor if the person has turned it on?

**Comment by Nicholas-Cardot** [comment]
Let's make sure that this is wrapped in a conditional so that it ONLY shows up if the user has share recovery activated in the settings.

Also, there is already a custom field that we allow folks to use, so let's make sure that when we create this field that it maps to the existing custom field key.

**Comment by Nicholas-Cardot** [comment]
This is the current custom field that it needs mapped to: swp_recovery_url
