### ISSUE TITLE
Create dashboard prompt requesting user reviews.

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#528]
Create a WordPress admin notice that will prompt users who have been using Social Warfare for [timeframe TBD] to leave a review on WordPress.org.

Notice must be: 
- [x] dismissible ("x" icon at the far right)
- [x] include a link to "leave a review"
- [x] include a link that says "I already have"

**Comment by DustinWStout** [comment]
Admin dashboard notice could look like this: 

<img width="801" alt="admin-notice-message" src="https://user-images.githubusercontent.com/2152604/38341803-4fe7edac-382f-11e8-9607-6d039ac8c886.png">

**Comment by DustinWStout** [comment]
Something like this could be really effective. 

<img width="949" alt="social-warfare-value-based-review-prompt" src="https://user-images.githubusercontent.com/2152604/39336256-5546cb9a-496b-11e8-91f3-a4e472dacad3.png">

This would mean we'd need a way to track how many shares a user is getting since installing.

**Comment by Nicholas-Cardot** [comment]
The class for this is now fully created. As notices are needed to encourage reviews, attempt upgrading users to pro, announcing news or sale events, these can all now be added as needed in a matter of minutes. As such, this issue is now being closed. The marketing team can simply let us know whenever they want a notice added, and we'll add it.
