### ISSUE TITLE
If SW not enabled for display, do not load metabox in admin - for CPTs

### ISSUE THREAD

**Issue by lisaleague** [warfare-plugins/social-warfare#53]
Example of an annoying situation where I don't want to have to close the metabox while adding or editing questions for quizzes in Sensei.

![screenshot-www qpractice com 2015-12-23 14-21-17](https://cloud.githubusercontent.com/assets/3607365/11983368/d6a499ac-a980-11e5-8ac8-e0352f6260cb.png)

**Comment by Nicholas-Cardot** [comment]
Unfortunately, this is not practical. Those exist because even though a user may not want to place them on most items in the post type, they may want to manually turn one on once in a while or they may want to at least set the meta data for a post. Additionally, we have no way of telling which post types are similar to posts versus which ones are completely unique systems like quizzes. 

However, the option to turn them off yourself for that post type already exists in two forms:
**1. Permanent Solution:** Click on screen options at the top of the page. Uncheck the Social Warfare custom option. It should now stop displaying forever on that post type.
**2. Temporary Solution:** Click the toggle on the panel itself to hide it or reveal it on each visit to the post editor in that post type.

Please check solution 1, and if it works, let's go ahead and close this. Thoughts?

CC: @lisaleague

**Comment by lisaleague** [comment]
Thanks @Nicholas-Cardot, 1 did work fine, thanks.

**Comment by Nicholas-Cardot** [comment]
@lisaleague Excellent! Thanks for the fast feedback!
