### ISSUE TITLE
Fail Gracefully on not supported PHP versions like 5.3

### ISSUE THREAD

**Issue by mehul0810** [warfare-plugins/social-warfare#536]
## Issue Overview
As a user, when I first install the Social Warfare (Production Version 3.0.5) with PHP 5.3 and then activated the plugin gives me fatal error due to array shorthands used in the code.

![image](https://user-images.githubusercontent.com/1852711/39963900-03f93baa-5696-11e8-8b60-b48715a56f0b.png)

## Expected Behaviour
If the plugin is not supporting PHP 5.3 then there should be a tag `Requires PHP Version` should be shown on plugin's WP.org profile. Also, If activated on PHP 5.3, the plugin should gracefully inform the user and not with a fatal error which is a bad UX.

## Steps to reproduce
1. Install WordPress on PHP Version 5.3
2. Install Social Warfare 3.0.5 from WP.org
3. Activate Social Warfare
4. Notice the fatal error on activating Social Warfare

## Additional Information
WordPress Version: 4.9.5
PHP Version: 5.3 (gives a fatal error) and above 5.4 (working fine)
Caching Plugin: No Caching plugin used

**Comment by Nicholas-Cardot** [comment]
Yeah, we only support versions of PHP in accordance with the versions that are supported by the official PHP community. You're asking us to make it gracefully fail on a version of PHP that received it's end of life nearly 4 years ago. You can look here to see which version of PHP we no longer support because they are no longer supported by the creators of PHP.

http://php.net/eol.php
