### ISSUE TITLE
Hide plugin version in HTML source code

### ISSUE THREAD

**Issue by valentinocossar** [warfare-plugins/social-warfare#548]
Hi, for security purposes, is possible to hide plugin version in the HTML source code? Is this something that necessarily has to be displayed in a comment in the HTML source code?

Thank you.

**Comment by DustinWStout** [comment]
Hi, @valentinocossar! Having the version number show in the source code helps save time when troubleshooting. 

For Feature Requests such as this, it's always best to send them to our team directly using the contact form on our website, rather than creating an "Issue" on Github (which tends to imply something is "wrong" with the plugin).
