### ISSUE TITLE
Update the layout of the sidebar in the settings page.

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#557]
# **Notes for Testers** 

Our admin sidebar was due for a makeover. Instead of static images, we can now deliver new HTML anytime we like. 

### What we want to happen: 
When on the Social Warfare settings page, you should see a new sidebar. 

## How to test: 
In the Social Warfare settings, you should see a new sidebar with three components (see image below). 

If you see the components and they look like the photo, hooray! We are good to go. 

If you do not yet have this side bar showing up, try adding this to the end of your URL: 
`&swp_debug=json_fetch`. A local site URL looks using that parameter looks like this: 
> https://beta.warfareplugins.com/wp-admin/admin.php?page=social-warfare&swp_debug=json_fetch

Load the page. It should look pretty bad with a lot of data printed on the screen. 
Remove the query parameter we just added. 
> https://beta.warfareplugins.com/wp-admin/admin.php?page=social-warfare

And load the page. 

If you see the components and they look like the photo, hooray! We are good to go. 

If the sidebar is still the old sidebar, please let us know as a comment to this issue. 

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**end notes**
#

no more images, just icons (we can tap into dashicons) and text and css.

also, would be amazing to have this update via .json file so we can update it with new content when needed without pushing a plugin update

- icon size: 40px
- heading size: 26px
- paragraph font size: 13px (wordpress default)
- container padding & margin between elements: 20px

<img width="175" alt="screen shot 2018-06-27 at 3 50 15 pm" src="https://user-images.githubusercontent.com/2152604/42003934-898e5d68-7a22-11e8-9951-0bcb9b20717f.png">

**Style guide:** https://warfareplugins.com/style-guide/

**Comment by DustinWStout** [comment]
small detail, but worth mentioning: notice that all text in the sidebar is center aligned _except_ the bullet list of features. bullet lists never look good center aligned.

**Comment by ckmahoney** [comment]
Create a Sidebar class which reads JSON from the server and displays it as markup. 
The object we create should have these components: 

Icon Code
Title
Text  (html)
CTA/Button

We should be able to edit the JSON sent from the warfareplugins.com/json_updates.php any time such that the Sidebar object in Social Warfare can interpret and render fully qualified HTML for each object.

**Comment by ckmahoney** [comment]
The sidebar is looking really good, and I am really excited about it.
But there are some limitations when using our JSON method for live updates to the admin:

1. All styles will need to be inline, or sent from our server. We can go ahead and ship out styles for the known sidebar components, but when we create new ones, they won’t have any style in the customer’s CSS. 
2. It must be in English without the ability to translate. Because this is coming from a plain non-WP PHP file from our server, we do not have access to gettext translations.

If we move the file into the /wp-content/ directory on warfareplugins.com, we should then gain access to gettext calls, but the request will be a teensy bit slower.

TODO: 

Create a filter `swp_admin_sidebar` that allows us to add components on the fly. 

Push the third component, "Need Help", into this filter so that we have access to the database for Get System Status.

**Comment by ckmahoney** [comment]
This issue has been notated and is ready for testing.

**Comment by DustinWStout** [comment]
Looks like it's still showing the "Upgrade to Pro" Box even though Pro is installed and activated. This should definitely be hidden for Pro users, otherwise I can foresee a LOT of support tickets complaining about it.

**Comment by Nicholas-Cardot** [comment]
The "Upgrade to Pro" should now be hidden when Pro is installed. Great catch.

**Comment by shaunacallaghan** [comment]
Tested with and without Pro installed. Working & looks great.

**Comment by coreyzev** [comment]
Tested, working. Only looks as good as the pictures when the window is greater than 1500px wide. Cards dont scale well. But they show up as expected. 

![image](https://user-images.githubusercontent.com/2052536/45306707-4c95cc80-b4eb-11e8-9fc8-da95fa6fa619.png)

**Comment by Nicholas-Cardot** [comment]
@coreyzev Good observations, but we can fix that up a little bit when we're working on making the admin options page more responsive in 3.4.
