### ISSUE TITLE
Still having major issues with upgrades

### ISSUE THREAD

**Issue by smerriman** [warfare-plugins/social-warfare#574]
It seems the problems with earlier 3.x versions of Social Warfare, that were meant to be resolved, are still not resolved.

On one site, last month, when I had 3.07 of both core + pro installed, an upgrade to 3.09 was showing for core, but no upgrade for pro. Running the upgrades left everything broken, with a message about needing to keep the versions in sync, but no way to upgrade, and the registration tab completely missing. Had to downgrade and fetch the latest versions from my account instead.

This month, another site had 3.09 installed for both, with updates to 3.11 showing for both. I click update for core, and then click update for Pro. Pro update fails. Registration tab missing. Have to downgrade, then upgrade Pro first, before upgrading core. This time it works.

This is nonsense. Please figure out a better way of resolving these issues.

**Comment by ckmahoney** [comment]
Hello @smerriman,

You are correct that currently our core and pro plugins are forced to be in sync as far as version numbers go, or else Pro breaks. This is a known issue and a problem we are working on. 

As of this morning we as a team have decided to prioritize it, especially since we now have a plan for multiple updates per month. 

Regarding "[problems] that were meant to be resolved, are still not resolved," can you please provide more detail?

**Comment by smerriman** [comment]
I was referring to posts like:

https://mailchi.mp/warfareplugins/important-update-for-social-warfare-305?e=[UNIQID]

or multiple posts throughout the WordPress support forums that the issues regarding upgrades had been resolved, when clearly they hadn't.

**Comment by Nicholas-Cardot** [comment]
This issue is being closed as a duplicate. These issues are being tracked in other, more specific issues here on GitHub.
