### ISSUE TITLE
Always display mobile float location 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#579]
# // **Notes for Testers** 

We have been expanding the mobile floating options. Sometimes things get a little misplaced. 

### What we want to happen: 
When viewing the settings at Social Warfare -> Styles -> Floating Share Buttons, the "On Mobile" dropdown should always be visible. 

 

### How to test: 
Social Warfare -> Styles -> Floating Share Buttons : 

1. Make sure "Floating Share Buttons" is on.
2. Set "Float Position" to "top" or "botttom".
3. Can you see the dropdown for "On Mobile"?
4. Set "Float Position" to "left" or "right".
5. Can you see the dropdown for "On Mobile"?

The answer to both 3 and 5 should be "Yes."

If everything goes as described, hooray! We are good to go. 
If something is contrary to what we describe, please let us know in a comment to this issue.

If something is not clear or the process does not make sense, please use Slack to ask questions. 

**// end notes**
#
#

Right now the mobile float location only appears as an option when floating buttons are set to top or bottom. 

We would like mobile float location to be an option when floaters are left/right as well. This affords admins the option to remove floating buttons on mobile, or at least change their position (in case there are advertisements or notifications where the buttons would go).

**Comment by nutsandbolts** [comment]
After dealing with display issues for a ticket, I think core should display all floating options except "inherit visual options" since they don't have visual options without Pro. Not being able to adjust these settings is a huge pain for people who are using core by itself.

**Comment by blogtutor** [comment]
I agree! This is a huge problem right now. Was just about to email you but then realized I should check here first. ;)

It's caused problems and confusion on many of my clients' sites, because the mobile setting is hidden, but still taking effect.  

When the "Float Position" is set to "Top of the Page," the mobile buttons do not necessarily follow that setting.  I have seen several sites where they have actually still been floating on the bottom on mobile.

To fix this, I have to change the Float Position to "Left side of the page," which then expands the rest of the settings. If I then change the "On mobile" setting to "Top of Screen," and then change the "Float Position" back to "Top of the page."  it will work correctly on mobile.

So...either the mobile setting needs to be always visible (to avoid this confusion!), or the master Float position setting, when set to "Top of the Page" needs to override whatever is hidden in the mobile-specific setting.

**Comment by Nicholas-Cardot** [comment]
@blogtutor If you want, you can pull the latest version from the testing branch here on GitHub and give it a spin. This one is fully complete and in the "ready for testing" phase of development. It will be included in our release next Monday.

In our new testing version, if the floaters are turned on at all, this option is always available.

I hope that helps!

**Comment by blogtutor** [comment]
Thanks Nick!

**Comment by JasonWiser** [comment]
tested. works
