### ISSUE TITLE
Pinterest Image Select Fallback

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#59]
For those users who have many popular posts before adding Social Warfare, they probably don't want to go back and recreate or reupload a Pinterest-specific image into the SW fields. Therefore, it would be nice to have a fallback where if no Pinterest-specififc image is declared in SW then it would give the reader the typical Pinterest share ability to select an image from the page.

**Comment by Nicholas-Cardot** [comment]
Here's the way it works:
1. If there is a Pinterest Image, we use that.
2. If not Pinterest image, we use the post thumbnail.
3. If not post thumbnail, we use the pinterest javascript and let the user select.

The goal is to make it so that the user doesn't have to select an image. We want it to be as close to a one-click share as possible.
