### ISSUE TITLE
Twitter Share Counts Have Been Deprecated

### ISSUE THREAD

**Issue by Nicholas-Cardot** [warfare-plugins/social-warfare#6]
Twitter recently removed the ability to query share counts from their services. We are currently working with Open Share Count (http://www.opensharecount.com) to remedy this.

**Comment by GrowMap** [comment]
Thanks Nicholas. We appreciate you working with opensharecount to get the Social Warfare plugin to handle this for us.

**Comment by Nicholas-Cardot** [comment]
@GrowMap Just so you're aware, we're intentionally moving slowly on this issue. There are several share count providers that have been created since Twitter removed theirs. As such, we are carefully examining each one to ensure that we integrate the right one that has the capacity to scale quickly across thousands of sites. Once we integrate a solution into Social Warfare, it will go out onto thousands of sites in a matter of days as people update the plugin.

We also have a few technical issues that need to be worked out. We want to ensure the the plugin continues to save any share counts that were fetched prior to Twitter shutting off their server. And we want to ensure that the numbers fetched from these share count services are added together with our cached numbers to provide the fullest and most accurate solution possible.

That being said, this is something that we'll probably look at having fully integrated right around the first week of next year. That should be plenty of time to have everything in place.

**Comment by dkornyukhov** [comment]
Awesome! Thanks for letting us know, Nick and thank you for all your hard work! Really appreciate all your efforts to make SW the most accurate share counting plugin.

**Comment by brugeman** [comment]
Hi, Nicholas.

How are things going with SW plugin? Just wanted to address some of your concerns (if you are still evaluating the available solutions and newsharecounts.com - NSC - among them):
1. NSC was integrated by several popular plugins and now serves more than 10M requests daily (13M yesterday). Current capacities allow us to serve up to 1000M requests daily, so it shouldn't be a problem to serve your users too.
2. NSC has some unique features, like fast tweet detection, more sites to be tracked by single twitter account, and lots of historic share counts. We serve the tracked and historic counts separately so that you could combine those numbers with the ones you cached and get the most accurate result.

If you have any concerns about capacities, quality or any other related to NSC, I'd really appreciate your feedback. 

Thanks.

**Comment by Nicholas-Cardot** [comment]
We're going to begin development on this today. We are going to begin with the solution provided by New Share Counts. Stay tuned for further development.

**Comment by Nicholas-Cardot** [comment]
It looks like we're going with NewShareCounts.com because they allow multiple domains per user and they seem to have a highly scalable infrastructure in place. We now have this installed and are in the final stages of testing.

**Comment by GrowMap** [comment]
Thank you, Nicholas. We are thrilled and trying to wait patiently. No
share counts drops retweets, clicks and traffic...Twitter must be vying
for the "Worst Decision By A Social Network EVER" award.

Gail Gardner
http://GrowMap.com
Linkedin.com/in/GrowMap
Skype username growmap
214-444-6247

CONFIDENTIALITY NOTICE. This message and any documents attached are for
the sole use of the intended recipient(s) and may contain confidential
and/or privileged information. Any unauthorized review, use, disclosure,
or distribution is prohibited. If you are not the intended recipient,
please destroy all copies of the original message, including any and all
attachments, and notify the sender immediately.
