### ISSUE TITLE
Ensure full plugin-wide compatibility with Gutenberg

### ISSUE THREAD

**Issue by VR51** [warfare-plugins/social-warfare#603]
## Notes for testers

**What we expect**
Social Warfare can be used with Gutenberg just as it was able to be used without Gutenberg.

**How to Test**

1. Install and activate the Gutenberg plugin.
2. Go to a post editor. Find the metabox Social Warfare, and change the post specific settings. Save the post. 
3. Browse a few pages on your admin, then return to the same post editor. Confirm that the settings are exactly how you left them. 
4. Repeat steps 2 and 3 a few times until you have updated every option at least once. 

If any of the steps do not go as described, please let us know as a response to this thread. 

Once you have finished testing, please give this comment a thumbs up. 
### end notes
The Pinterest button is displayed with the same width and height as the image it floats over. This seems to only happen with the Gutenberg Image Gallery block.

![image](https://user-images.githubusercontent.com/5859901/44288368-08a30500-a268-11e8-895e-840d465981ba.png)

**Comment by ckmahoney** [comment]
Hi @VR51 ,
Thank you for bringing this to our attention. We are aiming to be fully Gutenberg compatible by the end of October. 
As such, I will move this into our milestone for version 3.4.0 of Social Warfare, which is largely where we will be working on Gutenberg.

**Comment by ckmahoney** [comment]
After installing the Gutenberg plugin on my local site at testing with the SW custom options and shortcode, I am finding it to be all okay out of the box.

Compared to Show Hidden Post Meta, which does not seem to work out of the box with Gutenberg.

**Comment by DustinWStout** [comment]
I'm finding everything works just fine in my Gutenberg installs.

Only drawback is we don't have a block for Click-to-Tweets or Shortcodes so you have to first select a Classic block and use the Social Warfare icons for the respective functions. Which is fine, HOWEVER, not ideal because those buttons are distorting the Classic Block UI...

<img width="689" alt="screen shot 2018-11-05 at 3 18 50 pm" src="https://user-images.githubusercontent.com/2152604/48032897-27e65b80-e10e-11e8-8770-e962b9223a43.png">

Notice the Social Warfare icon and the Twitter icon pushing the More button outside the container...

<img width="703" alt="screen shot 2018-11-05 at 3 19 46 pm" src="https://user-images.githubusercontent.com/2152604/48032947-43e9fd00-e10e-11e8-95e5-170ac44c66a3.png">

**Comment by ckmahoney** [comment]
Are we doing anything with CSS that distorts the kitchen sink, or is that WP that is acting funny with it? 

I'm reading about creating Gutenberg Blocks now. I think it is possible to create a block for both CTT and the SW button, if we want that to happen this week. 

https://wordpress.org/gutenberg/handbook/block-api/

**Comment by ckmahoney** [comment]
Using this framework for block setup: 

https://github.com/ahmadawais/create-guten-block

**Comment by DustinWStout** [comment]
Awesome. Yea, block is the way to go... BUT there will be plenty of people who are dead set on sticking with the Classic editor as long as possible, so we should address/clean up the classic editor buttons too.

**Comment by meymigrou** [comment]
![pinterest-problem-with-gutenberg](https://user-images.githubusercontent.com/30810726/49038903-fb7ea600-f1c6-11e8-9ea2-3b6453966fe4.png)

I'm having the same problem with Gutenberg's gallery blocks.

 (WordPress 5.0-RC1-43944 running Twenty Nineteen theme.)
