### ISSUE TITLE
Add more link shortening services. 

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#608]
We currently only offer Bitly as a link shortening service, but would like to offer our customers more options. 

@Nicholas-Cardot , @DustinWStout , @nutsandbolts , please discuss in comments which services to a add and how we want to display this on the UI.

**Comment by nutsandbolts** [comment]
For now I think we'd be good adding Rebrandly since we get that request a lot. However, we definitely have to address the way short links are created since Rebrandly's free plan only allows up to 1k total.

**Comment by ckmahoney** [comment]
Writing on behalf of customer in Ticket ID 200503

Is there an API that does link matching? Rather than have a new link made by social warfare on a click, if I make a custom link, can Social Warfare through an API see the custom shortened link I’ve created and use that?

**Comment by Nicholas-Cardot** [comment]
Actually, we DON'T want to add more link shortening services. 

1. We want to rebuild our current link shortening processes into some sort of extendable class that makes it very easy to plugin new link shortening services.
2. We then want to make addons (1 addon per link shortener) so that users can select which link shortener they want and install just that link shortener instead of having 5 link shorteners bloating up the code. Just pick the one you want, install it, authenticate/login with it, and have your short links.

Does that make sense?

**Comment by ckmahoney** [comment]
Closing as a child of #609 .
