### ISSUE TITLE
Pinterest Button does not work on Safari & other mobile devices.

### ISSUE THREAD

**Issue by ckmahoney** [warfare-plugins/social-warfare#658]
TicketID 224211

We had previously thought that it was older models or older versions of the OS which caused the button to not work. However, customer reports saying they are using newer phones with near up-to-date OSs disprove this thought. 

Considering the quantity of tickets that come in on a regular basis about this one topic, it should be considered an issue that can satisfy many customers when solved.

**Comment by Nicholas-Cardot** [comment]
My theory: The JS is not being loaded and the click binds are therefore not working. 

Context: 
1. All of the buttons have href's and data-link attributes. These contain the share link.

2. We had to remove the href from the Pinterest button because instead of targeting a class or ID, the native Pinterest JS for their buttons targets an href with the share link in it. This was transforming our Pinterest buttons into their Pinterest buttons on websites where their native Pinterest JS was also present.

3. Our JS looks for the data-link and uses that to generate the share popout window.

4. If our JS doesn't load, all of the other buttons will fall back to the href and just open using the target="_blank" mechanism. However, Pinterest won't. This will create the appearance that the Pinterest button is broken, when really it's not. It's simply a symptom of the real problem...that the JS isn't loading.

**Comment by Nicholas-Cardot** [comment]
This should now be resolved.
