### ISSUE TITLE
Missing Campaign Parameters in Google Analytics

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#726]
See internal # 325314 for more info.

**Comment by Nicholas-Cardot** [comment]
These seem to appear properly in all of my tests.

**Comment by Nicholas-Cardot** [comment]
This may possibly have been caused by having a space character in the parameter. If a space is present, they will not appear in the UTM parameters. It cannot process spaces.

However, I've just added a find/replace method that will look for spaces and replace them with underscores to ensure that they get output properly in the UTM parameters of the URL. This should fully solve this issue.
