### ISSUE TITLE
[GH 733] Pinterest Title not displaying and/or custom pinterest description not being shared

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#733]
We are seeing a sudden increase in tickets reporting that Pinterest titles are not appearing.

**Comment by SquanchyMe** [comment]
Seeing more of these. Now tracking and collecting info

**Comment by SquanchyMe** [comment]
Internal ticket # 348107 - Sent latest patch, awaiting response
347163 - sent patch, awaiting response
348094 - refunded

**Comment by Nicholas-Cardot** [comment]
Here's some troubleshooting steps that will possibly help us to figure out what is going on.

1. Find a page where this is happening.
2. Identify the title/description that was specified and the title/description that is showing up in the share dialogue box. 
3. Try to identify where the shared title is coming from. Is it pulling it from the page title? The open graph title? A header (h1,h2) tag on the page somewhere? You may need to look at the source code and essentially do a search for the title/description to see if you can find it.
4. Are there more than one set of open graph tags on the page? Check the source code for this.
5. Are there any errors in the share link itself. For example, maybe this only happens when there are apostrophes in the share link. Or perhaps there is a another special character that makes it break whenever that character is present and we just need to encode it properly.

**Comment by SquanchyMe** [comment]
The issue may be two-fold.. 
A) Description not showing on the share-sheet. Now confirmed as a Pinterest issue (happening to many but not all sites, regarldess of the sharing plugin used)
B) The custom description not being shown on the Pin, after pinning.. I am waiting for examples of this from customers.

**Comment by Nicholas-Cardot** [comment]
It looks like Pinterest has made some changes at their end. Here's what we have found out so far:
1. This seems to be happening to other share plugins as well. It's not isolated to Social Warfare.
2. It appears that it only happens to some users. Likely a part of some features they are experimenting with that they've rolled out to some users and not to others. Hopefully, they become aware of these side effects of whatever they are working on and come up with a solution.
