### ISSUE TITLE
Undefined Index

### ISSUE THREAD

**Issue by DustinWStout** [warfare-plugins/social-warfare#76]
From the user who found this: 

I just updated to the latest version which caused some errors to display on the site

Undefined index: yummly in functions/social-networks/yummly.php line 72 
Undefined index: email in functions/social-networks/email.php line 65 
Undefined index: whatsapp in functions/social-networks/whatsapp.php line 73

I fixed it by going to the plugin settings for the site and disabling those 3 and hitting save. If it helps we are on a multisite install and I updated from the network admin.

**Comment by Nicholas-Cardot** [comment]
This is because no default setting was created for these options. I'll create a default setting for them in the next update. In the meantime, these indexes will automatically be created as soon as you save the options with them turned either one or off. The saving of the options will generate those indexes.
