### ISSUE TITLE
W3C Validation Error: Element a is missing required attribute href

### ISSUE THREAD

**Issue by SquanchyMe** [warfare-plugins/social-warfare#805]
Per customer:  an error in the W3C validator for the social media widget (Element a is missing required attribute href.)
See internal 394505 for more details if needed

**Comment by SquanchyMe** [comment]
Still in V4.2

**Comment by Nicholas-Cardot** [comment]
This is not something that we can or are willing to fix. That validation error does NOT hurt anything...at all. Not even a little bit. Adding the a tag makes it so that if the official Pinterest JavaScript is included on the page, they then hijack our button and style it to look like theirs. They target the href that includes their domain name. It's actually pretty crazy that they do that. So we moved our href to a different tag and handle it ourselves with our own Javascript instead. But, suffice it to say, fix this warning is NOT worth the headaches that it causes. The cure is far, far, far, far worse that the ailment in this case.
